name: Build & Deploy Vue to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. checkout your code
      - uses: actions/checkout@v3

      # 2. install Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '23'

      # 3. install dependencies & build
      - run: npm ci
      - run: npm run build

      # 4. deploy the `dist/` folder to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

